package edu.handong.csee.lapr;

public class PatchValidator {
	 
	public String getFinalPatches(Object patches) {
		//테스트케이스를 적용해 통과하는 patch를 찾느다
		System.out.println("//PATCH VALIDATION");
		System.out.println("test patches generated by getPatches method using test cases.");
		System.out.println("find patches that pass all test cases, and then select finalPatch to fix bug.");
		System.out.println("");
		return null;
	}
}
